### PR TITLE
Create new stencil after an expression in control flow

### LINKED ISSUE #261: StencilDescStatementMapper not correctly working with Ifs
If you have a stencil code such as:
```
#include "gridtools/clang_dsl.hpp"
using namespace gridtools::clang;
globals { int global = 0; };

stencil execute {
  storage in_field, out_field;
  void Do() {
    if(global) {
      global++;
      vertical_region(k_start, k_end) {
        // copy fields
        if(global > 0)
          out_field = in_field;
      }
      global--;
      vertical_region(k_start + 1, k_end) {
        if(global > 0)
          out_field = in_field;
      }
      global++;
    }
  }
};
```
the generated run method will be incorrect:
```
 void run() {
    if (m_globals.global) {
      (++m_globals.global);
      m_stencil_81.get_stencil()->run();
      (--m_globals.global);
      (++m_globals.global);
    }
  }
```
The problem is that `StencilDescStatementMapper` visitor in `OptimizerContext.cpp` will fuse the vertical regions together in the same stencil (but on different MultiStages) and substitute only the first encounter of a `VerticalRegionDeclStmt` with a stencil call, regardless of control flow statements that may be in between.

### LINKED ISSUE #401: Global does not enter into the data dependency of the fusion
#include "gridtools/clang_dsl.hpp"
using namespace gridtools::clang;
globals { bool global = false; };

stencil copystencil {
 storage in_field, out_field;
 void Do() {
   vertical_region(k_start, k_end)
{      // copy fields      out_field = in_field;    }
   global = true;
   vertical_region(k_start, k_end) {      // copy fields      out_field = in_field;    }

 }
};

### PR DESCRIPTION
**Pull request by havogt**
## Technical Description

Fixes #401, fixes #261.

### CODE REVIEW

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
Still need to add a test-case somewhere.

**Comment by Stagno** [comment]
This issue https://github.com/MeteoSwiss-APN/dawn/issues/261 is somehow related

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch perftest

**Comment by havogt** [comment]
Performance didn't change with respect to master (though the reference is outdated).

**Pull request merged**
