### PR TITLE
Switch to std::optional

### PR DESCRIPTION
**Pull request by havogt**
First c++17 feature to test compilers.

### CODE REVIEW

**Comment by havogt** [comment]
launch pipeline

**Comment by havogt** [comment]
launch pipeline

**Comment by twicki** [comment]
check the pipeline before the merge, seems to not be ok yet:
image

**Comment by havogt** [comment]
I believe it should be ignored as there is a PR chain down to clang-gridtools for switching the compiler.

**Comment by havogt** [comment]
Can you double-check? Then I would like to merge now.

**Comment by twicki** [comment]
Ah yeah, seems good.

**Pull request merged**
