### PR TITLE
Enable Temporary Fields in Weights

### PR DESCRIPTION
**Pull request by mroethlin**
## Technical Description

Using temporary fields as weights in a reduction was never explicitly disabled or prohibited from a design perspective. However, they were also untested. Recently, @BenWeber42 motivated their use in [this MR](https://gitlab.dkrz.de/dsl/icon-cscs/-/merge_requests/35) . Trying his proposal for a stencil involving temporary weights triggered a few problems in dawn:

* `ReplaceChildren` was not overwritten for the `ReduceOverNeighborExpr`
* The `ReduceOverNeighborExpr` equality function did not correctly forward the `compareData` argument
* The `ASTUtil::ExprReplacer` did not correctly replace expressions contained in `ReduceOverNeighborExpr` weights.

These issues led to incorrect working of `PassSetTemporaryType` and `PassRemoveScalars` where fields contained in weights were not properly demoted and scalar `VarAcccess`es not properly remove if contained in weights, respectively. 

### Testing

Two tests have been added to the testing facilities of the two affected passes. They are

```
def tempWeight(inF: Field[Cell], outF: Field[Edge], test: Field[Edge]):  
  tempF: Field[Edge]
  with domain.upward:
    tempF = test
    outF = sum_over(Edge > Cell, inF, weights=[tempF, tempF])   
```

and 

```
def tempWeight(inF: Field[Cell], outF: Field[Edge], test: Field[Edge]):  
  tempF: Field[Edge]
  with domain.upward:
    tempF = 1
    outF = sum_over(Edge > Cell, inF, weights=[tempF, 1-tempF])
```

This PR is also exercised in this [sten 14 of the icon integration](https://gitlab.dkrz.de/dsl/icon-cscs/-/merge_requests/35)

### Dependencies

If this PR is independent.

### CODE REVIEW

**Comment by mroethlin** [comment]
launch jenkins

**Comment by mroethlin** [comment]
launch jenkins

**Review by muellch — APPROVED** [review]
Took me a while to understand why the following line is not a problem, since it sets the length of the `operands_` vector to 2.

https://github.com/MeteoSwiss-APN/dawn/blob/f6fba7f6ba84fc9fdc55da9e75256379fd8b9093/dawn/src/dawn/AST/ASTExpr.h#L649

Then I discovered that `insert` saves the day.

https://github.com/MeteoSwiss-APN/dawn/blob/f6fba7f6ba84fc9fdc55da9e75256379fd8b9093/dawn/src/dawn/AST/ASTExpr.cpp#L475

**Comment by mroethlin** [comment]
launch jenkins

**Comment by mroethlin** [comment]
launch jenkins

**Pull request merged**
