### PR TITLE
Rework Subdomains

### PR DESCRIPTION
**Pull request by mroethlin**
## Technical Description

The subdomain mechanism is reworked to be consistent with the c++ and python conventions, see [here](https://jenkins-mch.cscs.ch:8081/job/icon-dsl-PR/) for a more detailed explanation. The consequence of this endeavor for dawn is that the `set_splitter_index_upper` and `set_splitter_index_lower` functions are replaced with a single `set_splitter_index` function.

### Dependencies

This PR is independent

### CODE REVIEW

**Comment by mroethlin** [comment]
launch jenkins

**Comment by mroethlin** [comment]
launch jenkins

**Comment by mroethlin** [comment]
launch jenkins

**Review by muellch — APPROVED** [review]
Looks good!

**Pull request merged**
