### PR TITLE
improves float32 compatibility

### PR DESCRIPTION
**Pull request by PanicSheep**
- Relaxes interface of functions 'min' and 'max' to take inputs of different types, because they are called with (double, float), where doubles for example stem from global variables.

- The default precision of the verifier for float is lowered so the dawn tests pass.

- Error prints the same values that caused the error.

- Removes one floating point operation in 'compare_below_threashold(..)' and thus one source of rounding error.

### Testing

Can be tested by setting '#define GT_FLOAT_PRECISION **4**' in "dawn/src/driver-includes/gridtools_includes.hpp".
It compiles and runs, but some automated tests fail because the numerical precision threshold isn't tuned yet. (Should we open a GitHub issue for that?)
The 'vertical_diffusion_uvw' benchmark produce nans and infs which makes the tests fail. (Should we open a GitHub issue for that?)

### CODE REVIEW

**Comment by Stagno** [comment]
launch jenkins

**Comment by Stagno** [comment]
> Can be tested by setting '#define GT_FLOAT_PRECISION 4' in "dawn/src/driver-includes/gridtools_includes.hpp".
It compiles and runs, but some automated tests fail because the numerical precision threshold isn't tuned yet. (Should we open a GitHub issue for that?)
The 'vertical_diffusion_uvw' benchmark produce nans and infs which makes the tests fail. (Should we open a GitHub issue for that?)

Is this information still up to date? @PanicSheep

**Review by Stagno — APPROVED** [review]

**Comment by PanicSheep** [comment]
@Stagno Yes, setting '#define GT_FLOAT_PRECISION 4' in "dawn/src/driver-includes/gridtools_includes.hpp" is still up to date. There were other problems though. But I was able to resolve them with PR: https://github.com/MeteoSwiss-APN/dawn/pull/1046.

I just ran the tests with GT_FLOAT_PRECISION 4 and this resulted in
```
The following tests FAILED:
	691 - GTClang-coriolis_stencil_gt_cuda_test (Failed)
	692 - GTClang-coriolis_stencil_cuda_cuda_test (Failed)
	718 - GTClang-tridiagonal_solve_gt_cuda_test (Failed)
	719 - GTClang-tridiagonal_solve_cuda_cuda_test (Failed)
```
```
691/740 Test #691: GTClang-coriolis_stencil_gt_cuda_test
...
[ RUN      ] coriolis_stencil.test
( 3, 7, 4 ) :  u_tens_gt = -0.00247389 ;  u_tens_cxxnaive = -0.00247395  error: 2.40935e-05
/usr/src/dawn/gtclang/test/integration-test/CodeGen/coriolis_stencil_benchmark.cpp:64: Failure
Value of: verif.verify(u_tens_gt, u_tens_cxxnaive)
```
```
692/740 Test #692: GTClang-coriolis_stencil_cuda_cuda_test
...
[ RUN      ] coriolis_stencil.test
( 3, 7, 4 ) :  u_tens_gt = -0.00247389 ;  u_tens_cxxnaive = -0.00247395  error: 2.40935e-05
/usr/src/dawn/gtclang/test/integration-test/CodeGen/coriolis_stencil_benchmark.cpp:64: Failure
```
```
718/740 Test #718: GTClang-tridiagonal_solve_gt_cuda_test
...
[ RUN      ] tridiagonal_solve.test
( 3, 3, 2 ) :  d_gt = -0.00551123 ;  d = -0.00551105  error: 3.32903e-05
( 3, 4, 1 ) :  d_gt = 0.0573344 ;  d = 0.0573358  error: 2.52752e-05
( 3, 4, 2 ) :  d_gt = 0.0890038 ;  d = 0.0890026  error: 1.31426e-05
( 4, 4, 0 ) :  d_gt = 1.15988 ;  d = 1.15984  error: 3.53553e-05
( 4, 4, 1 ) :  d_gt = -0.825857 ;  d = -0.825818  error: 4.7129e-05
( 4, 4, 2 ) :  d_gt = 0.320311 ;  d = 0.3203  error: 3.30299e-05
( 4, 4, 3 ) :  d_gt = 0.519877 ;  d = 0.519862  error: 2.90068e-05
( 4, 4, 4 ) :  d_gt = -0.40591 ;  d = -0.405889  error: 5.21289e-05
( 4, 4, 5 ) :  d_gt = 0.349758 ;  d = 0.349747  error: 2.93117e-05
( 4, 4, 6 ) :  d_gt = 0.244588 ;  d = 0.244584  error: 1.69976e-05
/usr/src/dawn/gtclang/test/integration-test/CodeGen/tridiagonal_solve_benchmark.cpp:66: Failure
```
```
719/740 Test #719: GTClang-tridiagonal_solve_cuda_cuda_test
...
[ RUN      ] tridiagonal_solve.test
( 3, 3, 2 ) :  d_gt = -0.00551123 ;  d = -0.00551105  error: 3.32903e-05
( 3, 4, 1 ) :  d_gt = 0.0573344 ;  d = 0.0573358  error: 2.52752e-05
( 3, 4, 2 ) :  d_gt = 0.0890038 ;  d = 0.0890026  error: 1.31426e-05
( 4, 4, 0 ) :  d_gt = 1.15988 ;  d = 1.15984  error: 3.53553e-05
( 4, 4, 1 ) :  d_gt = -0.825857 ;  d = -0.825818  error: 4.7129e-05
( 4, 4, 2 ) :  d_gt = 0.320311 ;  d = 0.3203  error: 3.30299e-05
( 4, 4, 3 ) :  d_gt = 0.519877 ;  d = 0.519862  error: 2.90068e-05
( 4, 4, 4 ) :  d_gt = -0.40591 ;  d = -0.405889  error: 5.21289e-05
( 4, 4, 5 ) :  d_gt = 0.349758 ;  d = 0.349747  error: 2.93117e-05
( 4, 4, 6 ) :  d_gt = 0.244588 ;  d = 0.244584  error: 1.69976e-05
/usr/src/dawn/gtclang/test/integration-test/CodeGen/tridiagonal_solve_benchmark.cpp:66: Failure
```

So the situation with float32 is improved but not perfect yet.

**Comment by PanicSheep** [comment]
I lowered the numerical precision threshold for the float tests. I know this might hide numerical crimes but at least all parts of the system are now compiling and running. Before that clang-gridtools wasn't compiled because the gtclang tests failed.

**Comment by PanicSheep** [comment]
launch jenkins

**Comment by PanicSheep** [comment]
@Stagno What's your opinion on lowering the precision?

**Comment by Stagno** [comment]
@PanicSheep Looking at the tests that were failing, it seems that the numbers are reasonably the same. The printed error is always between 1e-05 and 1e-04. Can't you use 1e-04 as threshold? 1e-02 seems too much.

**Comment by PanicSheep** [comment]
@Stagno Yes, you are absolutely right. This still makes the GTClang tests pass so the CI will go on to build the clang-gridtools tests.

**Pull request merged**
