### PR TITLE
Add ReduceOverNeighbor

### PR DESCRIPTION
**Pull request by lukasm91**
## Technical description

Adds ReduceOverNeighbor concept in the unstructured grid backend.

Requires #283, #285

### CODE REVIEW

**Comment by twicki** [comment]
This is still a hard replacement of the SIR with an in-memory generation of IIR. Should probably not go back?

**Comment by lukasm91** [comment]
Nope, should not go back. This is why I write that we need to see how to continue.

**Comment by lukasm91** [comment]
launch pipeline

**Comment by lukasm91** [comment]
launch pipeline

**Comment by lukasm91** [comment]
launch pipeline

**Pull request merged**
