### PR TITLE
Integrate python examples in CMake

### PR DESCRIPTION
**Pull request by havogt**
## Technical Description

Integrate python examples in CMake

TODO: move pip install test to separate jenkins plan

### CODE REVIEW

**Comment by twicki** [comment]
are you sure that this renaming ` dawn/test/unit-test/test_dawn4py/conftest.py` → `dawn/test/unit-test/dawn4py/conftest.py` did not disable this test?

**Comment by twicki** [comment]
I can work on getting the install test to work separately

**Comment by Stagno** [comment]
@havogt Could you also add `dawn/src/dawn4py/serialization/test/test_sir.py` to the tests run? They are passing.

**Comment by jdahm** [comment]
This has been incorporated into #677.

**Pull request closed without merging**
