### PR TITLE
Parallel model implementation

### PR DESCRIPTION
**Pull request by twicki**
## Technical Description

This branch tests the implementation of the parallel model

### Resolves / Enhances

fixes https://github.com/MeteoSwiss-APN/dawn/issues/836

### CODE REVIEW

**Comment by twicki** [comment]
launch jenkins

**Comment by jdahm** [comment]
launch jenkins

**Comment by twicki** [comment]
launch jenkins

**Comment by twicki** [comment]
launch jenkins

**Comment by twicki** [comment]
launch jenkins

**Comment by twicki** [comment]
launch jenkins

**Comment by twicki** [comment]
launch jenkins

**Pull request closed without merging**
