### PR TITLE
Add check_modularization script

### PR DESCRIPTION
**Pull request by lukasm91**
## Technical Description

Adds the `check_modularization.sh`-script from GridTools. Complains if we have unexpected dependencies between the modules defined in #238

### CODE REVIEW

**Comment by havogt** [comment]
I'd go for the githook as we already have it...

**Comment by lukasm91** [comment]
done. I also added some commented out dependencies that would be ideal to have, but are not there. Can you check the dependencies too?

**Comment by havogt** [comment]
Did you test the git hook? I tried to add a dependency in AST to IIR and didn't catch it.

**Comment by havogt** [comment]
Sorry. Typo on my side.

**Pull request merged**
