### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by havogt**
## Technical Description

Updates the Dockerfile to point to the new gtclang location

### CODE REVIEW

**Comment by havogt** [comment]
Do we test this somewhere?

**Comment by twicki** [comment]
the dockerfile is not automatically tested, no

**Comment by havogt** [comment]
Is someone using it? Then please test this change.

**Comment by jdahm** [comment]
I changed a few directory references to `gtclang`, and it seems to work correctly now.

**Comment by havogt** [comment]
Thanks!

**Pull request merged**
