### PR TITLE
fix python if stmt (#294)

### LINKED ISSUE #294: Python make_if_stmt is broken
```make_if_stmt``` in ```python/dawn/sir.py``` uses ```stmt.expr.*``` when it should use ```stmt.[cond,then,else]_part.*```. This is not picked up as there is no test for ```make_if_stmt``` in ```python/dawn/test_sir.py```

### PR DESCRIPTION
**Pull request by rupertford**
Fixes a bug in Python ```make_if_stmt()``` and adds an associated test. The code builds and runs for me and works with a simple if example. 

Fixes #294.

### CODE REVIEW

**Comment by twicki** [comment]
launch pipeline

**Comment by twicki** [comment]
we let the tests run through, I'll merge as soon as it passed

**Comment by twicki** [comment]
launch pipeline

**Comment by havogt** [comment]
ok to test

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
ok to test

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
Thanks for the fix and sorry for the delay!

**Pull request merged**
