### PR TITLE
Add Interface to set CUDA Stream

### PR DESCRIPTION
**Pull request by mroethlin**
## Technical Description

This PR allows setting the cuda stream in the setup function.

### Testing

Is tested using `icon-dsl` and `icondusk-e2e`

### Dependencies

This PR is independent.

### CODE REVIEW

**Comment by mroethlin** [comment]
launch jenkins

**Review by muellch — APPROVED** [review]
Looks good!

**Comment by mroethlin** [comment]
launch jenkins

**Comment by mroethlin** [comment]
launch jenkins

**Pull request merged**
