### PR TITLE
Add runWithoutSync()

### PR DESCRIPTION
**Pull request by havogt**
## Technical Description

For gt4py we need a run-method which doesn't call sync() on data_stores. This is a quickfix.

### CODE REVIEW

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
To not break API such a flag would have to go last with a default value. I thought it will look very ugly if you have a lot of fields (uniform arguments) and then an optional bool at the end.

**Comment by twicki** [comment]
Should have been more specific. I meant a dawn flag

**Comment by havogt** [comment]
This wasn't discussed. Actually I have no opinion here, all we do will be a hack...

**Comment by twicki** [comment]
I think it would be a little cleaner since it would make sure that the driver code looks the same (and would fix the comparison to generated code tests :wink:) but you are right, it is a temporary solution so I'm ok with either option

**Comment by havogt** [comment]
Replaced by #967

**Pull request closed without merging**
